import React, { useState } from 'react';
import { AISuggestions } from '../types';
import { 
  Sparkles, 
  BookOpen, 
  Code, 
  Award, 
  Layers, 
  CheckCircle2, 
  Copy, 
  Check 
} from 'lucide-react';

interface AIImprovementRoadmapProps {
  suggestions: AISuggestions;
}

export const AIImprovementRoadmap: React.FC<AIImprovementRoadmapProps> = ({ suggestions }) => {
  const [activeTab, setActiveTab] = useState<'summary' | 'bullets' | 'roadmap' | 'projects'>('summary');
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const handleCopy = (text: string, idx: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(idx);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <div className="p-6 sm:p-8 rounded-3xl glass-panel border border-slate-800 space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <h3 className="text-lg font-bold text-white flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-amber-400" />
            <span>AI Actionable Suggestions & Learning Roadmap</span>
          </h3>
          <p className="text-xs text-slate-400 mt-0.5">
            Tailored content suggestions generated by Gemini AI to upgrade your resume impact.
          </p>
        </div>

        {/* Tab switcher */}
        <div className="flex space-x-1 bg-slate-900 p-1 rounded-xl border border-slate-800">
          {(['summary', 'bullets', 'projects', 'roadmap'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold capitalize transition-colors ${
                activeTab === tab
                  ? 'bg-brand-600 text-white shadow-md'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              {tab}
            </button>
          ))}
        </div>
      </div>

      {/* Tab 1: Suggested Professional Summary */}
      {activeTab === 'summary' && (
        <div className="space-y-4">
          <div>
            <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">Suggested High-Impact Summary Statement</h4>
            <div className="p-4 bg-slate-900/90 rounded-2xl border border-slate-800 relative group">
              <p className="text-sm text-slate-200 leading-relaxed font-sans">
                {suggestions.suggestedProfessionalSummary || 'Tailored summary unavailable.'}
              </p>
              {suggestions.suggestedProfessionalSummary && (
                <button
                  onClick={() => handleCopy(suggestions.suggestedProfessionalSummary, 99)}
                  className="mt-3 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors"
                >
                  {copiedIndex === 99 ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedIndex === 99 ? 'Copied' : 'Copy Statement'}</span>
                </button>
              )}
            </div>
          </div>

          {suggestions.suggestedResumeHeadlines?.length > 0 && (
            <div>
              <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">Suggested Resume Headlines</h4>
              <div className="space-y-2">
                {suggestions.suggestedResumeHeadlines.map((headline, idx) => (
                  <div key={idx} className="p-3 bg-slate-900/60 rounded-xl border border-slate-800 flex items-center justify-between text-xs text-brand-300 font-semibold">
                    <span>{headline}</span>
                    <button
                      onClick={() => handleCopy(headline, idx + 100)}
                      className="text-slate-400 hover:text-white"
                    >
                      {copiedIndex === idx + 100 ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Tab 2: Suggested Bullet Points */}
      {activeTab === 'bullets' && (
        <div className="space-y-3">
          <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400">XYZ Formula Experience Bullet Points</h4>
          {suggestions.suggestedBulletPoints.map((bullet, idx) => (
            <div key={idx} className="p-4 bg-slate-900/80 rounded-2xl border border-slate-800 flex items-start justify-between gap-4">
              <div className="flex items-start gap-3">
                <span className="w-5 h-5 rounded-full bg-brand-500/10 text-brand-400 flex items-center justify-center shrink-0 text-xs font-bold mt-0.5">
                  {idx + 1}
                </span>
                <p className="text-xs sm:text-sm text-slate-200">{bullet}</p>
              </div>
              <button
                onClick={() => handleCopy(bullet, idx)}
                className="text-slate-400 hover:text-white shrink-0 p-1"
              >
                {copiedIndex === idx ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              </button>
            </div>
          ))}
        </div>
      )}

      {/* Tab 3: Suggested Projects & Certifications */}
      {activeTab === 'projects' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-3">
            <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
              <Code className="w-4 h-4 text-purple-400" />
              <span>Recommended Skill-Building Projects</span>
            </h4>
            <div className="space-y-2">
              {suggestions.suggestedProjects.map((p, i) => (
                <div key={i} className="p-3 bg-slate-900/80 rounded-xl border border-slate-800 text-xs font-semibold text-purple-300">
                  {p}
                </div>
              ))}
            </div>
          </div>

          <div className="space-y-3">
            <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
              <Award className="w-4 h-4 text-emerald-400" />
              <span>Recommended Certifications</span>
            </h4>
            <div className="space-y-2">
              {suggestions.suggestedCertifications.map((c, i) => (
                <div key={i} className="p-3 bg-slate-900/80 rounded-xl border border-slate-800 text-xs font-semibold text-emerald-300">
                  {c}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Tab 4: Learning Roadmap */}
      {activeTab === 'roadmap' && (
        <div className="space-y-3">
          <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
            <BookOpen className="w-4 h-4 text-brand-400" />
            <span>Target Learning Roadmap</span>
          </h4>
          <div className="space-y-3">
            {suggestions.suggestedLearningRoadmap.map((step, idx) => (
              <div key={idx} className="p-4 bg-slate-900/90 rounded-2xl border border-slate-800 flex items-start space-x-3">
                <div className="w-7 h-7 rounded-xl bg-brand-600/20 text-brand-400 border border-brand-500/30 flex items-center justify-center text-xs font-bold shrink-0">
                  {idx + 1}
                </div>
                <p className="text-xs sm:text-sm text-slate-200 font-medium">{step}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
